---

- hosts: Arla
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
      purge: yes
    when:
      - ansible_facts['distribution'] == "Ubuntu"

